const express=require('express');
const signupController = require('../controllers/signupcontroller');
const signinController = require('../controllers/signincontroller');
const getmusicController = require('../controllers/allmusicgetcontroller');
const verifyuserController = require('../controllers/verifycontroller');
const FetchUserProfileController = require('../controllers/fetchuserprofilecontroller');
const addartist = require('../controllers/postartist');
const getartistController = require('../controllers/getartistcontroller');
const routes=express.Router();
routes.post('/signup',signupController);
routes.post('/signin',signinController);
routes.get('/getmusics',verifyuserController,getmusicController);
routes.get('/getprofile',verifyuserController,FetchUserProfileController);
routes.post('/addartist',verifyuserController,addartist);
routes.get('/getartist',verifyuserController,getartistController);
module.exports=routes;